# Generated by Django 4.1.7 on 2023-02-27 10:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("citation", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "Categories"},
        ),
    ]
