# Generated by Django 4.1.7 on 2023-02-27 11:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("citation", "0002_alter_category_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="citation",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="citation",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
