# Generated by Django 4.1.7 on 2023-02-27 13:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("citation", "0003_citation_created_at_citation_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="citation",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
        ),
    ]
